train_params:
  experiment_name: "runs"
  model: yolo_nas_s
  pretrained_weights: coco
  num_workers: 0
  batch_size: 16
  num_classes: 19

  silent_mode: false
  average_best_models: true
  warmup_mode: "LinearEpochLRWarmup"
  warmup_initial_lr: 0.000001
  lr_warmup_epochs: 3
  initial_lr: 0.0005
  lr_mode: "cosine"
  cosine_final_lr_ratio: 0.1
  optimizer: "Adam"
  optimizer_params:
    weight_decay: 0.0001

  zero_weight_decay_on_bias_and_bn: true

  ema: true
  ema_params:
    decay: 0.9
    decay_type: "threshold"

  max_epochs: 384
  mixed_precision: true
  metric_to_watch: "mAP@0.50"

  loss:
    use_static_assigner: false
    reg_max: 16

  valid_metrics_list:
    score_thres: 0.1
    top_k_predictions: 300
    normalize_targets: true

  post_prediction_callback:
    score_threshold: 0.01
    nms_top_k: 1000
    max_predictions: 300
    nms_threshold: 0.7
  